# fly.toml app configuration file generated for flow-mind-api on 2024-05-01T19:05:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flow-mind-api'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
